### ISSUE TITLE
Proposal: use of fixtures

### ISSUE THREAD

**Issue by sacketty** [strongloop/loopback-testing#52]
Developers coming from rails might be missing usage of fixtures in the [FactoryGirlRails](http://github.com/thoughtbot/factory_girl_rails) way.
I am implementing a fork as an attempt to implement such a concept, with **belongsTo** and **hasMany** management between fixtures, while keeping compatibility with standard behavior.
Should I  submit [the code](https://github.com/sacketty/loopback-testing/tree/with/fixtures) as a fork, or as a new git ?

**Comment by bajtos** [comment]
I my opinion, the test fixtures (aka test data) should be build as part of the test code, see [building test data](https://github.com/strongloop/loopback-testing#building-test-data) and http://www.growing-object-oriented-software.com/.

Setting that aside, multiple small modules are easier to maintain because it's easier to delegate the maintenance of each part to a different person. I am proposing you to rework the code as a standalone module (github project) that can be used in addition with loopback-testing.

I am happy to add a link to loopback-testing's README mentioning your project, as long as you can submit the patch and include a short README section describing your project and where it may be useful.
